---

- name: Activity 1 Playbook

hosts: webservers

become: true

tasks:

- name: docker.io

apt:

force\_apt\_get: yes

update\_cache: yes

name: docker.io

state: present

- name: Install python3-pip

apt:

name: python3-pip

state: present

- name: Install docker

pip:

name: docker

state: present

- name: Install docker-container

docker\_container:

name: docker-container

image: cyberxsecurity/dvwa

state: started

published\_ports: 80:80
